name: bt_2025_models
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - requests
  - pyyaml
  - tqdm
  - sentencepiece
  - sqlite
  - tk
  - wheel

  - pip:
      - transformers
      - datasets
      - accelerate
      - safetensors
      - huggingface-hub
      - filelock
      - openpyxl
      - protobuf
      - regex
      - xxhash
      - multiprocess
      - pyarrow
